<?php

namespace EricPridham\Flow\Tests;

use EricPridham\Flow\FlowServiceProvider;
use EricPridham\Flow\Recorder\DatabaseRecorder;
use Orchestra\Testbench\TestCase;

class DatabaseTestCase extends TestCase
{
    protected function getPackageProviders($app): array
    {
        return [
            FlowServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
        $app['config']->set('flow.enabled', true);
        $app['config']->set('flow.recorders', [
            DatabaseRecorder::class
        ]);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('migrate', ['--database' => 'testbench']);
    }

    protected function runMigrations($app)
    {
        $this->artisan('migrate', ['--database' => 'testbench']);
    }
}
